/**
 * Bundled audio for the four fixed Upgrade Plan promotional samples.
 *
 * These clips never change at runtime, so they ship with the app instead of
 * being generated on demand. That is what makes the first tap immediate on a
 * fresh install and offline: there is no request, no generation, no download and
 * no credit to spend — the file is already on the device.
 *
 * ────────────────────────────────────────────────────────────────────────────
 * THE MAP BELOW IS GENERATED. Do not hand-edit it.
 *
 *   npm run generate:promo-voice
 *
 * The script writes the `PROMO_SAMPLE_AUDIO` literal between the two markers
 * from `PROMO_SAMPLE_TEXT` and the files it produced, so the map, the assets and
 * the spoken words cannot drift apart. Everything outside the markers is
 * hand-written and is preserved across regenerations.
 *
 * Until the script has run the map is empty, which is deliberate: `require()`ing
 * an asset that does not exist fails the Metro bundle, so an ungenerated build
 * must contain no entries at all. An empty map simply means every lookup misses
 * and `speakPromoSample` uses the existing `/v1/voice/promo` route, exactly as
 * it did before bundling — see the dev warning there.
 *
 * The generated version marker adds the same protection after pronunciation
 * or content changes: an older complete map remains buildable but is ignored
 * until the generator rewrites all clips and stamps the current promo version.
 * ────────────────────────────────────────────────────────────────────────────
 *
 * Every entry is a literal `require()` of a literal path. Nothing here is built
 * from a variable: Metro resolves asset references statically, so a computed
 * path would silently produce no asset at all.
 *
 * Pure module: no react-native and no expo imports, so it is unit-testable. A
 * `require()`d asset is a module id — a number — which is what `expo-audio`
 * accepts as an `AudioSource`.
 */

import {
  PROMO_SAMPLE_LANGS,
  PROMO_SAMPLE_VERSION,
  resolvePromoLang,
  type PromoSampleId,
  type PromoSampleLang,
} from './promoVoiceSamples';

/**
 * The languages promotional audio is generated for — the same 20 rows
 * `PROMO_SAMPLE_TEXT` carries. `resolvePromoLang` already narrows anything else
 * to one of these or to `en`.
 */
export const PROMO_AUDIO_LANGS = PROMO_SAMPLE_LANGS;

export type PromoAudioLang = PromoSampleLang;

/** One bundled clip per sample, for one language. */
export type PromoSampleAudioSet = Readonly<Record<PromoSampleId, number>>;

/* eslint-disable @typescript-eslint/no-var-requires */
/* PROMO_SAMPLE_AUDIO:BEGIN — generated by scripts/generate-promo-voice.mjs */
export const PROMO_SAMPLE_AUDIO_VERSION: string = 'upgrade-promo-v3';
export const PROMO_SAMPLE_AUDIO: Readonly<Partial<Record<PromoAudioLang, PromoSampleAudioSet>>> = {
  en: {
    spontaneous: require('../../assets/promo-voice/en/spontaneous.mp3'),
    vertical: require('../../assets/promo-voice/en/vertical.mp3'),
    merely: require('../../assets/promo-voice/en/merely.mp3'),
    morning_light: require('../../assets/promo-voice/en/morning_light.mp3'),
  },
  ja: {
    spontaneous: require('../../assets/promo-voice/ja/spontaneous.mp3'),
    vertical: require('../../assets/promo-voice/ja/vertical.mp3'),
    merely: require('../../assets/promo-voice/ja/merely.mp3'),
    morning_light: require('../../assets/promo-voice/ja/morning_light.mp3'),
  },
  ko: {
    spontaneous: require('../../assets/promo-voice/ko/spontaneous.mp3'),
    vertical: require('../../assets/promo-voice/ko/vertical.mp3'),
    merely: require('../../assets/promo-voice/ko/merely.mp3'),
    morning_light: require('../../assets/promo-voice/ko/morning_light.mp3'),
  },
  zh: {
    spontaneous: require('../../assets/promo-voice/zh/spontaneous.mp3'),
    vertical: require('../../assets/promo-voice/zh/vertical.mp3'),
    merely: require('../../assets/promo-voice/zh/merely.mp3'),
    morning_light: require('../../assets/promo-voice/zh/morning_light.mp3'),
  },
  es: {
    spontaneous: require('../../assets/promo-voice/es/spontaneous.mp3'),
    vertical: require('../../assets/promo-voice/es/vertical.mp3'),
    merely: require('../../assets/promo-voice/es/merely.mp3'),
    morning_light: require('../../assets/promo-voice/es/morning_light.mp3'),
  },
  fr: {
    spontaneous: require('../../assets/promo-voice/fr/spontaneous.mp3'),
    vertical: require('../../assets/promo-voice/fr/vertical.mp3'),
    merely: require('../../assets/promo-voice/fr/merely.mp3'),
    morning_light: require('../../assets/promo-voice/fr/morning_light.mp3'),
  },
  de: {
    spontaneous: require('../../assets/promo-voice/de/spontaneous.mp3'),
    vertical: require('../../assets/promo-voice/de/vertical.mp3'),
    merely: require('../../assets/promo-voice/de/merely.mp3'),
    morning_light: require('../../assets/promo-voice/de/morning_light.mp3'),
  },
  it: {
    spontaneous: require('../../assets/promo-voice/it/spontaneous.mp3'),
    vertical: require('../../assets/promo-voice/it/vertical.mp3'),
    merely: require('../../assets/promo-voice/it/merely.mp3'),
    morning_light: require('../../assets/promo-voice/it/morning_light.mp3'),
  },
  pt: {
    spontaneous: require('../../assets/promo-voice/pt/spontaneous.mp3'),
    vertical: require('../../assets/promo-voice/pt/vertical.mp3'),
    merely: require('../../assets/promo-voice/pt/merely.mp3'),
    morning_light: require('../../assets/promo-voice/pt/morning_light.mp3'),
  },
  ru: {
    spontaneous: require('../../assets/promo-voice/ru/spontaneous.mp3'),
    vertical: require('../../assets/promo-voice/ru/vertical.mp3'),
    merely: require('../../assets/promo-voice/ru/merely.mp3'),
    morning_light: require('../../assets/promo-voice/ru/morning_light.mp3'),
  },
  ar: {
    spontaneous: require('../../assets/promo-voice/ar/spontaneous.mp3'),
    vertical: require('../../assets/promo-voice/ar/vertical.mp3'),
    merely: require('../../assets/promo-voice/ar/merely.mp3'),
    morning_light: require('../../assets/promo-voice/ar/morning_light.mp3'),
  },
  hi: {
    spontaneous: require('../../assets/promo-voice/hi/spontaneous.mp3'),
    vertical: require('../../assets/promo-voice/hi/vertical.mp3'),
    merely: require('../../assets/promo-voice/hi/merely.mp3'),
    morning_light: require('../../assets/promo-voice/hi/morning_light.mp3'),
  },
  tr: {
    spontaneous: require('../../assets/promo-voice/tr/spontaneous.mp3'),
    vertical: require('../../assets/promo-voice/tr/vertical.mp3'),
    merely: require('../../assets/promo-voice/tr/merely.mp3'),
    morning_light: require('../../assets/promo-voice/tr/morning_light.mp3'),
  },
  nl: {
    spontaneous: require('../../assets/promo-voice/nl/spontaneous.mp3'),
    vertical: require('../../assets/promo-voice/nl/vertical.mp3'),
    merely: require('../../assets/promo-voice/nl/merely.mp3'),
    morning_light: require('../../assets/promo-voice/nl/morning_light.mp3'),
  },
  vi: {
    spontaneous: require('../../assets/promo-voice/vi/spontaneous.mp3'),
    vertical: require('../../assets/promo-voice/vi/vertical.mp3'),
    merely: require('../../assets/promo-voice/vi/merely.mp3'),
    morning_light: require('../../assets/promo-voice/vi/morning_light.mp3'),
  },
  th: {
    spontaneous: require('../../assets/promo-voice/th/spontaneous.mp3'),
    vertical: require('../../assets/promo-voice/th/vertical.mp3'),
    merely: require('../../assets/promo-voice/th/merely.mp3'),
    morning_light: require('../../assets/promo-voice/th/morning_light.mp3'),
  },
  id: {
    spontaneous: require('../../assets/promo-voice/id/spontaneous.mp3'),
    vertical: require('../../assets/promo-voice/id/vertical.mp3'),
    merely: require('../../assets/promo-voice/id/merely.mp3'),
    morning_light: require('../../assets/promo-voice/id/morning_light.mp3'),
  },
  pl: {
    spontaneous: require('../../assets/promo-voice/pl/spontaneous.mp3'),
    vertical: require('../../assets/promo-voice/pl/vertical.mp3'),
    merely: require('../../assets/promo-voice/pl/merely.mp3'),
    morning_light: require('../../assets/promo-voice/pl/morning_light.mp3'),
  },
  el: {
    spontaneous: require('../../assets/promo-voice/el/spontaneous.mp3'),
    vertical: require('../../assets/promo-voice/el/vertical.mp3'),
    merely: require('../../assets/promo-voice/el/merely.mp3'),
    morning_light: require('../../assets/promo-voice/el/morning_light.mp3'),
  },
  sv: {
    spontaneous: require('../../assets/promo-voice/sv/spontaneous.mp3'),
    vertical: require('../../assets/promo-voice/sv/vertical.mp3'),
    merely: require('../../assets/promo-voice/sv/merely.mp3'),
    morning_light: require('../../assets/promo-voice/sv/morning_light.mp3'),
  },
};
/* PROMO_SAMPLE_AUDIO:END */
/* eslint-enable @typescript-eslint/no-var-requires */

/**
 * The bundled clip for a sample in the requested language, or null.
 *
 * Language resolution is `resolvePromoLang`'s and nobody else's, so the audio
 * that plays is the audio for the words on screen. Unsupported input has already
 * resolved to `en`. A missing clip for a supported language returns null so the
 * network route can fetch that language; it must never substitute an English
 * bundle beneath localized text.
 */
export function bundledPromoAudio(
  sample: PromoSampleId,
  langCode: string | undefined,
): number | null {
  if (PROMO_SAMPLE_AUDIO_VERSION !== PROMO_SAMPLE_VERSION) return null;
  const lang = resolvePromoLang(langCode);
  return PROMO_SAMPLE_AUDIO[lang]?.[sample] ?? null;
}

/** Every bundled clip for one language, for preparing them together. */
export function bundledPromoAudioSet(langCode: string | undefined): readonly number[] {
  if (PROMO_SAMPLE_AUDIO_VERSION !== PROMO_SAMPLE_VERSION) return [];
  const lang = resolvePromoLang(langCode);
  const set = PROMO_SAMPLE_AUDIO[lang];
  return set ? Object.values(set) : [];
}
