import type { AudioFormat } from './config';

/** Duration of the generated bytes that the client will cache and play. */
export function audioDurationMs(bytes: ArrayBuffer, format: AudioFormat): number | null {
  const data = new Uint8Array(bytes);
  const view = new DataView(bytes);
  if (format === 'wav') {
    if (data.length < 44 || ascii(data, 0, 4) !== 'RIFF' || ascii(data, 8, 4) !== 'WAVE') return null;
    let byteRate = 0;
    let dataBytes = 0;
    for (let at = 12; at + 8 <= data.length;) {
      const tag = ascii(data, at, 4);
      const declared = view.getUint32(at + 4, true);
      // Streaming WAV can use an unknown-size marker until the stream ends.
      const size = tag === 'data' && declared === 0xffffffff
        ? data.length - at - 8 : declared;
      if (size > data.length - at - 8) return null;
      if (tag === 'fmt ' && size >= 16) byteRate = view.getUint32(at + 16, true);
      if (tag === 'data') dataBytes += size;
      at += 8 + size + (size % 2);
    }
    return byteRate > 0 && dataBytes > 0 ? Math.ceil(dataBytes * 1_000 / byteRate) : null;
  }

  let at = 0;
  if (ascii(data, 0, 3) === 'ID3' && data.length >= 10) {
    at = 10 + ((data[6]! & 0x7f) << 21) + ((data[7]! & 0x7f) << 14)
      + ((data[8]! & 0x7f) << 7) + (data[9]! & 0x7f);
    if (data[5]! & 0x10) at += 10;
  }
  let frames = 0;
  let duration = 0;
  while (at + 4 <= data.length) {
    const a = data[at]!, b = data[at + 1]!, c = data[at + 2]!;
    if (a !== 0xff || (b & 0xe0) !== 0xe0 || (b & 0x06) !== 0x02) {
      if (frames > 0) break; // A trailing tag or junk after valid frames.
      at += 1;
      continue;
    }
    const version = (b >> 3) & 0x03;
    const rateIndex = (c >> 4) & 0x0f;
    const sampleIndex = (c >> 2) & 0x03;
    if (version === 1 || rateIndex === 0 || rateIndex === 15 || sampleIndex === 3) {
      if (frames > 0) return null;
      at += 1;
      continue;
    }
    const bitrateTable = version === 3
      ? [0, 32, 40, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 256, 320]
      : [0, 8, 16, 24, 32, 40, 48, 56, 64, 80, 96, 112, 128, 144, 160];
    const bitrate = bitrateTable[rateIndex]! * 1_000;
    const sampleRate = [44_100, 48_000, 32_000][sampleIndex]! / (version === 3 ? 1 : version === 2 ? 2 : 4);
    const samples = version === 3 ? 1152 : 576;
    const frameBytes = Math.floor((version === 3 ? 144 : 72) * bitrate / sampleRate) + (c & 0x02 ? 1 : 0);
    if (!bitrate || !frameBytes || at + frameBytes > data.length) return null;
    duration += samples * 1_000 / sampleRate;
    frames += 1;
    at += frameBytes;
  }
  return frames > 0 ? Math.ceil(duration) : null;
}

function ascii(data: Uint8Array, at: number, length: number): string {
  return String.fromCharCode(...data.subarray(at, at + length));
}
